import { Urbanist } from "next/font/google";
import "./globals.css";
import GSAPWrapper from "@/components/elements/gsapWrapper";
import Navbar from "@/components/layouts/navbar";

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"]
})

export const metadata = {
  title: "Larasati Maharani",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${urbanist.variable} overflow-x-hidden antialiased`}
        suppressHydrationWarning
      >
        <Navbar />
        <GSAPWrapper>
          {children}
        </GSAPWrapper>
      </body>
    </html>
  );
}
