import { Geist_Mono, Instrument_Serif, Manrope } from "next/font/google";
import "./globals.css";
import GSAPWrapper from "@/components/elements/gsapWrapper";
import Navbar from "@/components/layouts/navbar";
import Contact from "@/components/layouts/contact";
import Footer from "@/components/layouts/footer";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"]
});

const serif = Instrument_Serif({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: "400"
});

const mono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"]
});

export const metadata = {
  title: "Larasati Maharani",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${manrope.variable} ${serif.variable} ${mono.variable} overflow-x-hidden antialiased`}
        suppressHydrationWarning
      >
        <Navbar />
        <GSAPWrapper>
          {children}
          <Contact />
          <Footer />
        </GSAPWrapper>
      </body>
    </html>
  );
}
